name: FTPS Deploy

on:
  push:
    branches:
      - main   # main branch'a push olduğunda çalışır

jobs:
  deploy-via-ftps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean unnecessary files
        run: |
          rm -rf .git .github tests storage
          rm -f .env clearall.php composer.lock package-lock.json phpunit.xml README.md

      - name: Deploy via FTPS using lftp
        run: |
          sudo apt-get update && sudo apt-get install -y lftp

          lftp -c "
            set ssl:verify-certificate no;
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ftp:passive-mode true;
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}:21;
            mirror -R --delete --verbose --exclude-glob .git* . ${{ secrets.FTP_SERVER_DIR }};
            quit
          "

      - name: Deploy completed
        run: echo "✅ Deployment completed successfully!"
