name: FTP Deploy

on:
  push:
    branches:
      - main   # main branch'a push olduğunda çalışır

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: FTP ile yükle
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          protocol: ftps
          security: loose
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/tests/**
            **/storage/**
            **/.env
            **/clearall.php
            **/composer.lock
            **/package-lock.json
            **/phpunit.xml
            **/README.md
