name: FTP Deploy

on:
  push:
    branches:
      - main   # main branch'a push olduğunda çalışır

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Gereksiz dosyaları sil
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf tests
          rm -rf storage
          rm -f .env
          rm -f clearall.php
          rm -f composer.lock
          rm -f package-lock.json
          rm -f phpunit.xml
          rm -f README.md

      - name: FTPS ile yükle
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_dir: ${{ secrets.FTP_SERVER_DIR }}
          secure: true
